name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    container: pandoc/latex

    steps:
      # Checkout the repository with additional options to include .dotfiles
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history to ensure correct context
          lfs: true # Include Git LFS files
          persist-credentials: false
          dotfiles: true # Ensure dotfiles are included (e.g., .gitignore)

      # Install mustache for processing
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      # Create the output directory
      - name: Create output
        run: sh ./build.sh

      # Push output to another repository
      - name: Push output to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: hyeonseok98
          destination-repository-name: Hobiday
          target-branch: main
          commit-message: ${{ github.event.commits[0].message }}
          user-email: ${{ secrets.EMAIL }}
          keep-files: true # Ensure existing files are not removed

      # Test exported variable
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
